language: c++

addons:
  apt:
    packages:
     - cmake
     - qtbase5-dev
     - libqt5opengl5-dev
     - libqwt-qt5-dev
     - libboost-dev
     - libeigen3-dev
     - libmysqlclient-dev
     - libmysqlcppconn-dev
     - libsqlite3-dev
     - liblog4cpp5-dev
     - libgdal-dev
     - libtinyxml2-dev
     - libarchive-dev
     - libjsoncpp-dev

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake build -- -j2

